In [1]:
# STEP 1: IMPORTING LIBRARIES
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
# STEP 2: LOADING THE DATASET
df=pd.read_excel("/content/track4_mid_day_meal_procurement.xlsx")
df

,procurement_id,date,school_id,vendor_name,grain_type,quantity,unit,total_cost,payment_status
0,MDM008522,2026/01/14,SCH0249,Singh Brothers,WHEAT,NaN,NaN,336/-,PENDING
1,MDM010158,2025-08-10,SCH0140,kumar general store,gehun,40.7,KGS,1221,Cleared
2,MDM007882,03/11/2025,SCH-0514,kumar general store,Oil,54.2,KGS,6504,Paid
3,MDM004875,2026/03/19,SCH-0445,sharma traders pvt ltd,RICE,0.8,50kg Bags,"Rs. 1,600",Due
4,MDM011422,16.08.2025,sch_0172,Kumar Supplies,chawal,NaN,NaN,"Rs. 2,104",Paid
...,...,...,...,...,...,...,...,...,...
12355,MDM011965,28-Nov-2025,S0499,S. Agro Works,Atta,27400,g,NaN,Cleared
12356,MDM005192,20.09.2025,SCH0386,Singh Brothers,Dal,NaN,NaN,"5,148/-",paid
12357,MDM005391,01.02.2026,SCH0587,Sharma Traders,Lentils,NaN,NaN,"5,292/-",NaN
12358,MDM000861,2025-07-29,SCH0457,kumar general store,Wheat,11.3,kg,339,Cleared
12359,MDM007271,2025-12-22,SCH-0153,sharma traders pvt ltd,Chawal,28,KG,"₹1,120",Pending

In [6]:
# STEP 3: DATA EXPLORATION

In [3]:
df.head()

,procurement_id,date,school_id,vendor_name,grain_type,quantity,unit,total_cost,payment_status
0,MDM008522,2026/01/14,SCH0249,Singh Brothers,WHEAT,NaN,NaN,336/-,PENDING
1,MDM010158,2025-08-10,SCH0140,kumar general store,gehun,40.7,KGS,1221,Cleared
2,MDM007882,03/11/2025,SCH-0514,kumar general store,Oil,54.2,KGS,6504,Paid
3,MDM004875,2026/03/19,SCH-0445,sharma traders pvt ltd,RICE,0.8,50kg Bags,"Rs. 1,600",Due
4,MDM011422,16.08.2025,sch_0172,Kumar Supplies,chawal,NaN,NaN,"Rs. 2,104",Paid

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12360 entries, 0 to 12359
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   procurement_id  12360 non-null  object
 1   date            12360 non-null  object
 2   school_id       12360 non-null  object
 3   vendor_name     12360 non-null  object
 4   grain_type      12360 non-null  object
 5   quantity        10451 non-null  object
 6   unit            8556 non-null   object
 7   total_cost      11714 non-null  object
 8   payment_status  10641 non-null  object
dtypes: object(9)
memory usage: 869.2+ KB

In [5]:
df.shape

(12360, 9)

In [8]:
df.describe()

,procurement_id,date,school_id,vendor_name,grain_type,quantity,unit,total_cost,payment_status
count,12360,12360,12360,12360,12360,10451.0,8556,11714,10641
unique,12000,2175,3165,12,18,1984.0,12,5552,6
top,MDM011193,2025-09-21,SCH0520,Kumar & Co.,Sarson Tel,40.1,KG,1476,Due
freq,2,18,19,1085,805,18.0,944,14,1834

In [9]:
df.columns

Index(['procurement_id', 'date', 'school_id', 'vendor_name', 'grain_type',
       'quantity', 'unit', 'total_cost', 'payment_status'],
      dtype='object')

In [10]:
df.dtypes

procurement_id    object
date              object
school_id         object
vendor_name       object
grain_type        object
quantity          object
unit              object
total_cost        object
payment_status    object
dtype: object

In [11]:
# STEP 4:CHECK FOR MISSING VALUES AND INVALID VALUES

In [12]:
df.isnull().sum()

procurement_id       0
date                 0
school_id            0
vendor_name          0
grain_type           0
quantity          1909
unit              3804
total_cost         646
payment_status    1719
dtype: int64

In [13]:
(df.isnull().sum() / len(df)) * 100

procurement_id     0.000000
date               0.000000
school_id          0.000000
vendor_name        0.000000
grain_type         0.000000
quantity          15.444984
unit              30.776699
total_cost         5.226537
payment_status    13.907767
dtype: float64

In [14]:
df.duplicated().sum()

np.int64(360)

In [15]:
df[df.duplicated()]

,procurement_id,date,school_id,vendor_name,grain_type,quantity,unit,total_cost,payment_status
341,MDM000748,2026-03-07,SCH0193,Sharma & Sons,Lentils,20.2 kg,NaN,1818,Cleared
470,MDM001278,02/02/2026,sch0440,Singh Brothers,Gehun,45.4,Kgs,"₹1,362",Paid
631,MDM004093,09-02-2025,SCH0409,Kumar & Co.,Rice,NaN,NaN,528,Due
697,MDM003099,30.06.2025,SCH0586,Kumar & Co.,Pulses,NaN,NaN,"Rs. 1,530",Pending
815,MDM002445,2025/12/02,SCH0424,kumar general store,Daal,NaN,NaN,"Rs. 5,247",Paid
...,...,...,...,...,...,...,...,...,...
12178,MDM006900,2025/11/29,SCH-0499,S. Agro Works,Sarson Tel,42000,g,5040,Cleared
12249,MDM008558,27.10.2025,sch_0496,Kumar Supplies,Pulses,40.2,Kgs,"₹3,618",paid
12257,MDM001942,13.10.2025,SCH-0414,Singh Brothers,Wheat,NaN,NaN,1377,NaN
12291,MDM003858,2025-09-21,S0303,Goyal Rice Mill,Gehun,50900,Grams,NaN,Due
12333,MDM000100,07.08.2025,SCH0409,Goyal Rice Mill,Sarson Tel,NaN,NaN,"5,700/-",NaN

In [16]:
for column in df.columns:
    print("\nColumn:", column)
    print(df[column].unique()[:20])

Column: procurement_id
['MDM008522' 'MDM010158' 'MDM007882' 'MDM004875' 'MDM011422' 'MDM007746'
 'MDM003693' 'MDM001497' 'MDM001214' 'MDM005465' 'MDM011101' 'MDM011169'
 'MDM004084' 'MDM008099' 'MDM009206' 'MDM002217' 'MDM001670' 'MDM000813'
 'MDM011888' 'MDM008145']

Column: date
['2026/01/14' '2025-08-10' '03/11/2025' '2026/03/19' '16.08.2025'
 '10-Apr-2025' '2025/08/05' '09/12/2025' '06-25-2025' '14.06.2025'
 '2025-10-10' '02-11-2026' '04.06.2025' '27.08.2025' '08-27-2025'
 '01-Oct-2025' '23.03.2026' '25.11.2025' '06.02.2026' '03/10/2025']

Column: school_id
['SCH0249' 'SCH0140' 'SCH-0514' 'SCH-0445' 'sch_0172' 'sch0357' 'S0267'
 'sch0210' 'SCH0301' 'SCH-0233' 'sch0283' '0113' 'SCH0037' 'S0340' 'S0366'
 'SCH0462' 'S0228' 'SCH0492' 'SCH0321' 'S0462']

Column: vendor_name
['Singh Brothers' 'kumar general store' 'sharma traders pvt ltd'
 'Kumar Supplies' 'Singh Agro' 'Sharma & Sons' 'S. Agro Works'
 'Goyal Rice Mill' 'goyal mill' 'Sharma Traders' 'Kumar & Co.'
 'Goyal Enterprises']

Column: grain_type
['WHEAT' 'gehun' 'Oil' 'RICE' 'chawal' 'dal' 'Daal' 'Wheat' 'Atta'
 'Chawal' 'Pulses' 'Mustard Oil' 'Cooking Oil' 'Sarson Tel' 'Dal' 'Gehun'
 'Rice' 'Lentils']

Column: quantity
[nan 40.7 54.2 0.8 '14.9 kg' 16100 '14.2 kg' 57 28.5 '33.0 kg' 39.6 21.5
 0.5539999999999999 37 0.8959999999999999 41900 16.3 52.5 '46.6 kg'
 0.7120000000000001]

Column: unit
[nan 'KGS' '50kg Bags' 'Grams' 'KG' 'Kgs' 'Bori' 'Sacks' 'g' 'kg' 'Bags'
 'grams' 'bags']

Column: total_cost
['336/-' 1221 6504 'Rs. 1,600' 'Rs. 2,104' '596' 2826 '₹644' 1278
 '1,710/-' '855/-' 1320 '1188' 'Rs. 645' 'Rs. 2,493' 'Rs. 1,800' '4,440/-'
 'Rs. 1,344' nan 'Rs. 3,159']

Column: payment_status
['PENDING' 'Cleared' 'Paid' 'Due' nan 'paid' 'Pending']

In [17]:
df.select_dtypes(include="object").columns

Index(['procurement_id', 'date', 'school_id', 'vendor_name', 'grain_type',
       'quantity', 'unit', 'total_cost', 'payment_status'],
      dtype='object')

In [18]:
for column in df.select_dtypes(include="object").columns:
    print("\nColumn:", column)
    print(df[column].value_counts().head(20))

Column: procurement_id
procurement_id
MDM011193    2
MDM005944    2
MDM002632    2
MDM003708    2
MDM005404    2
MDM010044    2
MDM008030    2
MDM003419    2
MDM001571    2
MDM007589    2
MDM001176    2
MDM011794    2
MDM011075    2
MDM001744    2
MDM008721    2
MDM001370    2
MDM009080    2
MDM000462    2
MDM001435    2
MDM004641    2
Name: count, dtype: int64

Column: date
date
2025-09-21     18
2025-10-23     15
31-Mar-2026    15
29/03/2026     15
26/04/2025     15
2026-02-19     15
09/10/2025     15
2026-03-18     15
07/07/2025     14
2025/06/01     14
22.03.2026     14
18/08/2025     14
08-14-2025     14
03/03/2026     14
29/09/2025     13
06/05/2025     13
04/08/2025     13
22-Feb-2026    13
28/10/2025     13
13.04.2025     13
Name: count, dtype: int64

Column: school_id
school_id
SCH0520    19
SCH0226    18
SCH0283    17
SCH0159    17
SCH0080    17
SCH0531    17
SCH0498    17
SCH0136    17
SCH0364    17
SCH0323    17
SCH0445    17
SCH0259    16
SCH0186    16
SCH0102    16
SCH0361    16
SCH0013    16
SCH0203    16
SCH0440    16
SCH0399    15
SCH0388    15
Name: count, dtype: int64

Column: vendor_name
vendor_name
Kumar & Co.               1085
Singh Brothers            1084
kumar general store       1052
Kumar Supplies            1044
Singh Agro                1034
S. Agro Works             1027
Sharma & Sons             1026
Goyal Enterprises         1020
goyal mill                1008
sharma traders pvt ltd    1006
Sharma Traders             993
Goyal Rice Mill            981
Name: count, dtype: int64

Column: grain_type
grain_type
Sarson Tel     805
Oil            801
RICE           792
Chawal         785
Cooking Oil    776
Rice           769
chawal         751
Mustard Oil    690
Pulses         670
dal            647
Daal           640
gehun          635
Lentils        627
WHEAT          613
Wheat          612
Dal            601
Gehun          576
Atta           570
Name: count, dtype: int64

Column: quantity
quantity
40.1     18
39.4     16
40.5     16
41.7     16
46       15
22.1     15
28.5     14
43.9     14
45.4     14
11.9     14
48.2     14
0.634    14
20.4     14
10.8     13
49.8     13
55.9     13
11.8     13
45.9     13
44       13
30.4     13
Name: count, dtype: int64

Column: unit
unit
KG           944
kg           906
Kgs          891
KGS          869
Grams        819
grams        802
g            801
Sacks        511
bags         505
50kg Bags    503
Bori         503
Bags         502
Name: count, dtype: int64

Column: total_cost
total_cost
1476         14
972          11
1656         11
1272         11
1728         11
1368         11
936          11
2184         10
1764         10
1608          9
Rs. 1,452     9
Rs. 1,644     9
1107          9
₹3,600        9
1800          9
₹2,340        9
1752          9
1620          9
Rs. 612       9
1,308/-       9
Name: count, dtype: int64

Column: payment_status
payment_status
Due        1834
paid       1830
Pending    1792
Paid       1770
Cleared    1708
PENDING    1707
Name: count, dtype: int64

In [19]:
df.describe().T

                  count  unique          top  freq
procurement_id    12360   12000    MDM011193     2
date              12360    2175   2025-09-21    18
school_id         12360    3165      SCH0520    19
vendor_name       12360      12  Kumar & Co.  1085
grain_type        12360      18   Sarson Tel   805
quantity        10451.0  1984.0         40.1  18.0
unit               8556      12           KG   944
total_cost        11714    5552         1476    14
payment_status    10641       6          Due  1834

In [21]:
df["date"].head()

0    2026/01/14
1    2025-08-10
2    03/11/2025
3    2026/03/19
4    16.08.2025
Name: date, dtype: object

In [22]:
# STEP 5:DATA CLEANING

In [23]:
# Create a copy so the original raw data remains unchanged
clean_df = df.copy()

for column in clean_df.select_dtypes(include="object").columns:
    clean_df[column] = clean_df[column].str.strip()

missing_values = ["", "NA", "N/A", "na", "n/a", "null", "None", "-"]

clean_df = clean_df.replace(missing_values, np.nan)

clean_df.head()

,procurement_id,date,school_id,vendor_name,grain_type,quantity,unit,total_cost,payment_status
0,MDM008522,2026/01/14,SCH0249,Singh Brothers,WHEAT,NaN,NaN,336/-,PENDING
1,MDM010158,2025-08-10,SCH0140,kumar general store,gehun,NaN,KGS,NaN,Cleared
2,MDM007882,03/11/2025,SCH-0514,kumar general store,Oil,NaN,KGS,NaN,Paid
3,MDM004875,2026/03/19,SCH-0445,sharma traders pvt ltd,RICE,NaN,50kg Bags,"Rs. 1,600",Due
4,MDM011422,16.08.2025,sch_0172,Kumar Supplies,chawal,NaN,NaN,"Rs. 2,104",Paid

In [58]:
# Create a cleaning copy
clean_df = df.copy()

In [59]:
# Remove duplicate rows
clean_df = clean_df.drop_duplicates()

# Remove extra spaces from text columns
for col in clean_df.select_dtypes(include="object").columns:
    clean_df[col] = clean_df[col].str.strip()

print("Duplicates remaining:", clean_df.duplicated().sum())

Duplicates remaining: 0

In [60]:
# Standardize school_id
import re

def clean_school_id(value):
    if pd.isna(value):
        return value

    number = re.search(r"\d+", str(value))

    if number:
        return "SCH" + number.group().zfill(4)

    return np.nan

clean_df["school_id"] = clean_df["school_id"].apply(clean_school_id)

clean_df["school_id"].head()

0    SCH0249
1    SCH0140
2    SCH0514
3    SCH0445
4    SCH0172
Name: school_id, dtype: object

In [61]:
# Standardize the date format
clean_df["date"] = pd.to_datetime(
    clean_df["date"],
    format="mixed",
    errors="coerce",
    dayfirst=True
)

clean_df["date"] = clean_df["date"].dt.strftime("%Y-%m-%d")

clean_df["date"].head()

0    2026-01-14
1    2025-08-10
2    2025-11-03
3    2026-03-19
4    2025-08-16
Name: date, dtype: object

In [62]:
print("Invalid dates:", clean_df["date"].isna().sum())

Invalid dates: 0

In [63]:
# Standardize vendor names
clean_df["vendor_name"] = (clean_df["vendor_name"].str.lower().str.strip())
vendor_map = {
    "sharma traders pvt ltd": "Sharma Traders",
    "sharma traders private limited": "Sharma Traders",
    "sharma trader": "Sharma Traders",
    "sharma traders": "Sharma Traders",

    "singh brother": "Singh Brothers",
    "singh brothers": "Singh Brothers",

    "kumar and co": "Kumar & Co.",
    "kumar co": "Kumar & Co.",

    "kumar general store": "Kumar General Store",
    "kumar supplies": "Kumar Supplies",
    "goyal rice mill": "Goyal Rice Mill"
}

clean_df["vendor_name"] = clean_df["vendor_name"].replace(vendor_map)

clean_df["vendor_name"].head()

0         Singh Brothers
1    Kumar General Store
2    Kumar General Store
3         Sharma Traders
4         Kumar Supplies
Name: vendor_name, dtype: object

In [64]:
# Standardize grain names
grain_map = {
    "rice": "Rice",
    "chawal": "Rice",

    "wheat": "Wheat",
    "gehun": "Wheat",

    "dal": "Lentils",
    "daal": "Lentils",
    "lentils": "Lentils",

    "pulses": "Pulses",
    "pulse": "Pulses",

    "sarson": "Mustard",
    "mustard": "Mustard"
}

clean_df["grain_type"] = (
    clean_df["grain_type"]
    .str.lower()
    .replace(grain_map)
)

clean_df["grain_type"].head()

0    Wheat
1    Wheat
2      oil
3     Rice
4     Rice
Name: grain_type, dtype: object

In [65]:
# Convert all quantities to kilograms
def convert_to_kg(value):
    if pd.isna(value):
        return np.nan

    value = str(value).lower().replace(",", "")

    number = re.search(r"\d+(?:\.\d+)?", value)

    if not number:
        return np.nan

    number = float(number.group())

    if "gram" in value or re.search(r"\bg\b", value):
        return number / 1000

    if "bag" in value or "sack" in value or "bori" in value:
        return number * 50

    return number

In [66]:
# Clean total_cost
clean_df["total_cost"] = (
    clean_df["total_cost"]
    .astype(str)
    .str.replace(",", "", regex=False)
    .str.extract(r"(\d+(?:\.\d+)?)")[0]
)

clean_df["total_cost"] = pd.to_numeric(
    clean_df["total_cost"],
    errors="coerce"
)

clean_df["total_cost"].head()

0     336.0
1       NaN
2       NaN
3    1600.0
4    2104.0
Name: total_cost, dtype: float64

In [72]:
for column in ["total_cost"]:
    clean_df[column] = clean_df[column].fillna(clean_df[column].median())

In [67]:
# Standardize payment status
payment_map = {
    "paid": "Paid",
    "cleared": "Cleared",
    "pending": "Pending",
    "due": "Due",
    "unpaid": "Unpaid"
}

clean_df["payment_status"] = (
    clean_df["payment_status"]
    .str.lower()
    .replace(payment_map)
)

clean_df["payment_status"].head()

0    Pending
1    Cleared
2       Paid
3        Due
4       Paid
Name: payment_status, dtype: object

In [68]:
categorical_columns = [
    "vendor_name",
    "grain_type",
    "unit",
    "payment_status"
]

for col in categorical_columns:
    clean_df[col] = clean_df[col].fillna(
        clean_df[col].mode()[0]
    )

In [69]:
import re
import numpy as np
import pandas as pd

def convert_to_kg(value):
    if pd.isna(value):
        return np.nan

    value = str(value).lower().strip()
    value = value.replace(",", "")

    # Get the number from the value
    number_match = re.search(r"\d+(?:\.\d+)?", value)

    if number_match is None:
        return np.nan

    number = float(number_match.group())

    # Convert grams to kilograms
    if "gram" in value or re.search(r"\bg\b", value):
        return number / 1000

    # Convert bags, sacks, and boris to kilograms
    elif "bag" in value or "sack" in value or "bori" in value:
        return number * 50

    # KG or no unit: treat as kilograms
    else:
        return number

In [70]:
clean_df["quantity_kg"] = clean_df["quantity"].apply(convert_to_kg)

display(clean_df[["quantity", "unit", "quantity_kg"]].head(20))

print("Missing quantity values:", clean_df["quantity_kg"].isna().sum())
clean_df["quantity_kg"] = clean_df["quantity_kg"].fillna(
    clean_df["quantity_kg"].median()
)
clean_df["quantity"] = clean_df["quantity_kg"]

clean_df = clean_df.drop(columns=["quantity_kg"])

   quantity       unit  quantity_kg
0       NaN         KG          NaN
1       NaN        KGS          NaN
2       NaN        KGS          NaN
3       NaN  50kg Bags          NaN
4       NaN         KG          NaN
5   14.9 kg         KG         14.9
6       NaN         KG          NaN
7       NaN      Grams          NaN
8   14.2 kg         KG         14.2
9       NaN        KGS          NaN
10      NaN        KGS          NaN
11  33.0 kg         KG         33.0
12      NaN         KG          NaN
13      NaN        Kgs          NaN
14      NaN       Bori          NaN
15      NaN         KG          NaN
16      NaN        KGS          NaN
17      NaN      Sacks          NaN
18      NaN          g          NaN
19      NaN         kg          NaN

Missing quantity values: 10156

In [74]:
# Make a copy of the cleaned data
clean_df = clean_df.copy()

# Standardize all unit values to KG
clean_df["unit"] = "KG"

# Check the result
print(clean_df["unit"].unique())

display(clean_df[["quantity", "unit"]].head(20))

['KG']

    quantity unit
0       33.9   KG
1       33.9   KG
2       33.9   KG
3       33.9   KG
4       33.9   KG
5       14.9   KG
6       33.9   KG
7       33.9   KG
8       14.2   KG
9       33.9   KG
10      33.9   KG
11      33.0   KG
12      33.9   KG
13      33.9   KG
14      33.9   KG
15      33.9   KG
16      33.9   KG
17      33.9   KG
18      33.9   KG
19      33.9   KG

In [ ]:
# FINAL VALIDATION

In [83]:
print("Dataset shape:", clean_df.shape)

print("\nMissing values:")
print(clean_df.isnull().sum())

print("\nDuplicate rows:")
print(clean_df.duplicated().sum())

display(clean_df.head())

Dataset shape: (12000, 10)

Missing values:
procurement_id          0
date                    0
school_id               0
vendor_name             0
grain_type              0
quantity                0
unit                    0
total_cost              0
payment_status          0
quantity_was_imputed    0
dtype: int64

Duplicate rows:
0

,procurement_id,date,school_id,vendor_name,grain_type,quantity,unit,total_cost,payment_status,quantity_was_imputed
0,MDM008522,2026-01-14,SCH0249,Singh Brothers,Wheat,33.9,KG,336.0,Pending,True
1,MDM010158,2025-08-10,SCH0140,Kumar General Store,Wheat,33.9,KG,1794.0,Cleared,False
2,MDM007882,2025-11-03,SCH0514,Kumar General Store,oil,33.9,KG,1794.0,Paid,False
3,MDM004875,2026-03-19,SCH0445,Sharma Traders,Rice,33.9,KG,1600.0,Due,False
4,MDM011422,2025-08-16,SCH0172,Kumar Supplies,Rice,33.9,KG,2104.0,Paid,True

In [84]:
from google.colab import files

# Remove the column
clean_df = clean_df.drop(columns=["quantity_was_imputed"])

# Save the updated CSV
clean_df.to_csv(
    "track4_mid_day_meal_procurement_cleaned.csv",
    index=False
)

# Download the CSV
files.download("track4_mid_day_meal_procurement_cleaned.csv")

In [86]:
print("Total rows:", len(clean_df))

print("Missing quantities:", clean_df["quantity"].isna().sum())

print("Missing units:", clean_df["unit"].isna().sum())

print("Unique units:", clean_df["unit"].unique())

print("Duplicate rows:", clean_df.duplicated().sum())

Total rows: 12000
Missing quantities: 0
Missing units: 0
Unique units: ['KG']
Duplicate rows: 0

In [87]:
clean_df.to_csv(
    "track4_mid_day_meal_procurement_cleaned.csv",
    index=False
)

print("Cleaned procurement file saved successfully!")

Cleaned procurement file saved successfully!

In [88]:
from google.colab import files

# Save the cleaned DataFrame as a CSV file
clean_df.to_csv(
    "track4_mid_day_meal_procurement_cleaned.csv",
    index=False
)

# Download the CSV to your computer
files.download("track4_mid_day_meal_procurement_cleaned.csv")