# Test Score Data Cleaning

**Project:** Student Retention & Welfare Tracker  
**Role:** Person 2 — Data Analysis & Data Science

This notebook focuses on inspecting, cleaning, standardizing, and validating
the student test-score dataset.

The final cleaned dataset will be saved as:

`data/processed/test_scores_clean.csv`

In [1]:
import pandas as pd
import numpy as np
import json

In [2]:
with open("../data/raw/track4_test_scores.json", "r", encoding="utf-8") as f:
    test_scores_raw = json.load(f)

In [3]:
type(test_scores_raw)

list

In [4]:
len(test_scores_raw)

8000

In [5]:
test_scores_raw[0]

{'assessment_id': 'TST005495',
 'date': '2025/05/05',
 'school_id': 'sch0083',
 'grade': '8',
 'subject': 'English',
 'grading_scale': 'Letter Grade',
 'avg_score': 'C',
 'max_marks': 'NA',
 'total_students_assessed': 125}

In [6]:
test_scores = pd.DataFrame(test_scores_raw)

In [7]:
test_scores.head()

,assessment_id,date,school_id,grade,subject,grading_scale,avg_score,max_marks,total_students_assessed
0,TST005495,2025/05/05,sch0083,8,English,Letter Grade,C,NA,125
1,TST003026,01.07.2025,sch0103,5,Punjabi,pct,63.4%,100,76
2,TST006793,06-Mar-2026,sch_0147,7,Math,CGPA,7.7,10,123
3,TST001798,2025-05-25,SCH0267,5,Science,Percentage,73.0%,100,34
4,TST005946,2026-03-18,SCH0254,6,Ganit,CGPA,4.8,10,148

In [8]:
test_scores.shape

(8000, 9)

In [9]:
test_scores.columns.tolist()

['assessment_id',
 'date',
 'school_id',
 'grade',
 'subject',
 'grading_scale',
 'avg_score',
 'max_marks',
 'total_students_assessed']

In [10]:
test_scores.info()

<class 'pandas.DataFrame'>
RangeIndex: 8000 entries, 0 to 7999
Data columns (total 9 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   assessment_id            8000 non-null   str
 1   date                     8000 non-null   str
 2   school_id                8000 non-null   str
 3   grade                    8000 non-null   str
 4   subject                  8000 non-null   str
 5   grading_scale            8000 non-null   str
 6   avg_score                8000 non-null   str
 7   max_marks                8000 non-null   object
 8   total_students_assessed  8000 non-null   int64
dtypes: int64(1), object(1), str(7)
memory usage: 912.8+ KB

In [11]:
test_scores.duplicated().sum()

np.int64(0)

In [12]:
test_scores["assessment_id"].duplicated().sum()

np.int64(0)

In [13]:
test_scores["grading_scale"].value_counts()

grading_scale
Raw Marks       2002
Letter Grade    1983
CGPA            1609
%                816
pct              800
Percentage       790
Name: count, dtype: int64

In [14]:
test_scores["subject"].value_counts()

subject
Hindi          1051
English        1022
Punjabi        1017
Ganit           996
EVS             994
Math            986
Mathematics     972
Science         962
Name: count, dtype: int64

In [15]:
test_scores["grade"].value_counts()

grade
8    1412
6    1336
5    1325
7    1316
4    1308
3    1303
Name: count, dtype: int64

In [16]:
test_scores["date"].value_counts().head(20)

date
2025-06-18     13
2025-06-26     12
2026-02-12     11
2025-12-22     11
2025-08-31     11
10-20-2025     10
25.01.2026     10
07-17-2025     10
2026-03-08     10
03.12.2025     10
26/06/2025     10
02.05.2025     10
2025/09/04     10
29-Aug-2025    10
11.10.2025     10
26/02/2026      9
2025-10-25      9
2025-05-16      9
19/02/2026      9
29-May-2025     9
Name: count, dtype: int64

In [17]:
test_scores["school_id"].value_counts().head(20)

school_id
SCH0502    14
SCH0154    14
SCH0276    13
SCH0482    13
SCH0533    13
SCH0082    13
SCH0228    13
SCH0557    13
SCH0048    12
SCH0386    12
SCH0319    12
SCH0285    12
SCH0147    11
SCH0208    11
SCH0335    11
SCH0192    11
SCH0038    11
SCH0078    11
SCH0392    11
SCH0284    11
Name: count, dtype: int64

In [18]:
test_scores["avg_score"].value_counts().head(30)

avg_score
C      563
D      550
B      529
E      187
A       79
A+      75
7.7     40
4.2     38
5.8     37
8.8     36
9.1     35
6.0     35
6.6     35
9.4     35
4.5     34
5.5     34
6.5     33
8.0     33
7.3     32
5.2     32
6.7     32
6.8     32
7.2     32
9.3     32
5.1     31
4.4     31
7.8     31
5.9     31
7.0     31
6.3     31
Name: count, dtype: int64

In [19]:
test_scores.groupby("grading_scale")["avg_score"].apply(
    lambda x: x.head(15).tolist()
)

grading_scale
%               [89.3%, 55.8%, 66.3%, 89.7%, 92.5%, 59.8%, 63....
CGPA            [7.7, 4.8, 8.8, 8.5, 8.9, 7.9, 6.2, 4.6, 5.1, ...
Letter Grade       [C, A+, B, D, C, D, C, C, C, C, C, B, B, B, A]
Percentage      [73.0%, 55.6%, 63.3%, 61.8%, 92.4%, 44.4%, 85....
Raw Marks       [21.6/50, 40.1/50, 16.0/25, 15.0/25, 45.0/50, ...
pct             [63.4%, 43.0%, 85.8%, 76.7%, 84.7%, 41.9%, 48....
Name: avg_score, dtype: object

In [20]:
test_scores.groupby("grading_scale")["max_marks"].apply(
    lambda x: x.head(15).tolist()
)

grading_scale
%               [100, 100, 100, 100, 100, 100, 100, 100, 100, ...
CGPA            [10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 1...
Letter Grade    [NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, N...
Percentage      [100, 100, 100, 100, 100, 100, 100, 100, 100, ...
Raw Marks       [50, 50, 25, 25, 50, 100, 50, 25, 50, 100, 25,...
pct             [100, 100, 100, 100, 100, 100, 100, 100, 100, ...
Name: max_marks, dtype: object

In [21]:
test_scores["max_marks"].value_counts(dropna=False).head(30)

max_marks
100    3061
NA     1983
10     1609
50      690
25      657
Name: count, dtype: int64

In [22]:
test_scores["avg_score"].isna().sum()

np.int64(0)

In [23]:
print("Duplicate rows:", test_scores.duplicated().sum())
print("Duplicate assessment IDs:", test_scores["assessment_id"].duplicated().sum())

Duplicate rows: 0
Duplicate assessment IDs: 0

## Step 1 — Test Score Standardization

The test-score dataset contains multiple grading scales, including:

- Percentage (`%`, `pct`, `Percentage`)
- Raw Marks
- CGPA
- Letter Grade

To make scores comparable across schools, grades, and subjects, all scores are
standardized to a percentage scale from 0 to 100.

The original `avg_score` and `grading_scale` columns are retained for traceability,
while a new `score_percentage` column is created for analysis.

In [24]:
raw_marks = test_scores.loc[
    test_scores["grading_scale"] == "Raw Marks",
    "avg_score"
]

raw_marks.head(20).tolist()

['21.6/50',
 '40.1/50',
 '16.0/25',
 '15.0/25',
 '45.0/50',
 '83.1/100',
 '27.9/50',
 '12.6/25',
 '30.6/50',
 '41.0/100',
 '14.3/25',
 '10.9/25',
 '19.6/25',
 '10.2/25',
 '21.1/50',
 '59.8/100',
 '54.6/100',
 '17.6/25',
 '36.0/50',
 '20.2/25']

In [25]:
raw_marks.str.contains(r"^\d+(\.\d+)?/\d+$", regex=True).value_counts()

C:\Users\helle\AppData\Local\Temp\ipykernel_30136\1683309826.py:1: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  raw_marks.str.contains(r"^\d+(\.\d+)?/\d+$", regex=True).value_counts()

avg_score
True    2002
Name: count, dtype: int64

In [26]:
percentage_scales = test_scores[
    test_scores["grading_scale"].isin(["%", "pct", "Percentage"])
]["avg_score"]

percentage_scales.head(20).tolist()

['63.4%',
 '73.0%',
 '43.0%',
 '85.8%',
 '76.7%',
 '55.6%',
 '84.7%',
 '89.3%',
 '63.3%',
 '41.9%',
 '61.8%',
 '48.2%',
 '55.8%',
 '82.2%',
 '92.4%',
 '66.3%',
 '87.5%',
 '44.4%',
 '41.0%',
 '46.3%']

In [27]:
percentage_scales.str.contains(
    r"^\d+(\.\d+)?%$",
    regex=True
).value_counts()

C:\Users\helle\AppData\Local\Temp\ipykernel_30136\2963530446.py:1: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  percentage_scales.str.contains(

avg_score
True    2406
Name: count, dtype: int64

In [28]:
test_scores.loc[
    test_scores["grading_scale"] == "Letter Grade",
    "avg_score"
].value_counts()

avg_score
C     563
D     550
B     529
E     187
A      79
A+     75
Name: count, dtype: int64

In [29]:
test_scores_clean = test_scores.copy()

In [30]:
def convert_to_percentage(row):
    scale = row["grading_scale"]
    score = row["avg_score"]
    
    # Percentage-based scores
    if scale in ["%", "pct", "Percentage"]:
        return float(str(score).replace("%", "").strip())
    
    # CGPA scores
    elif scale == "CGPA":
        return float(score) * 9.5
    
    # Raw marks such as 21.6/50 or 16.0/25
    elif scale == "Raw Marks":
        score_value, max_value = str(score).split("/")
        return (float(score_value) / float(max_value)) * 100
    
    # Letter grades
    elif scale == "Letter Grade":
        grade_mapping = {
            "A+": 95,
            "A": 85,
            "B": 75,
            "C": 65,
            "D": 55,
            "E": 45
        }
        return grade_mapping.get(str(score).strip())
    
    return np.nan

In [31]:
test_scores_clean["score_percentage"] = test_scores_clean.apply(
    convert_to_percentage,
    axis=1
)

In [32]:
test_scores_clean[
    ["grading_scale", "avg_score", "score_percentage"]
].head(20)

   grading_scale avg_score  score_percentage
0   Letter Grade         C             65.00
1            pct     63.4%             63.40
2           CGPA       7.7             73.15
3     Percentage     73.0%             73.00
4           CGPA       4.8             45.60
5   Letter Grade        A+             95.00
6           CGPA       8.8             83.60
7      Raw Marks   21.6/50             43.20
8            pct     43.0%             43.00
9   Letter Grade         B             75.00
10          CGPA       8.5             80.75
11  Letter Grade         D             55.00
12          CGPA       8.9             84.55
13           pct     85.8%             85.80
14           pct     76.7%             76.70
15    Percentage     55.6%             55.60
16          CGPA       7.9             75.05
17     Raw Marks   40.1/50             80.20
18     Raw Marks   16.0/25             64.00
19  Letter Grade         C             65.00

In [33]:
test_scores_clean["score_percentage"].describe()

count    8000.000000
mean       66.063937
std        15.047539
min        38.000000
25%        55.000000
50%        65.000000
75%        77.100000
max        95.000000
Name: score_percentage, dtype: float64

In [34]:
test_scores_clean["score_percentage"].isna().sum()

np.int64(0)

In [35]:
print("Missing standardized scores:",
      test_scores_clean["score_percentage"].isna().sum())

print("Scores below 0:",
      (test_scores_clean["score_percentage"] < 0).sum())

print("Scores above 100:",
      (test_scores_clean["score_percentage"] > 100).sum())

Missing standardized scores: 0
Scores below 0: 0
Scores above 100: 0

## Step 2 — Date Standardization

The raw test-score dataset contains dates in multiple formats, including:

- `YYYY-MM-DD`
- `YYYY/MM/DD`
- `DD.MM.YYYY`
- `DD/MM/YYYY`
- `DD-MM-YYYY`
- `MM-DD-YYYY`
- `DD-MMM-YYYY`

These formats are converted into a single standardized date format.

The cleaned dates are stored in the `date_clean` column using the
`YYYY-MM-DD` format.

Where numeric dates are ambiguous, the structure of the date is examined
carefully to avoid incorrectly swapping the day and month values.

In [36]:
test_scores_clean["date_clean"] = pd.to_datetime(
    test_scores_clean["date"],
    errors="coerce",
    dayfirst=False
)

In [37]:
print("Invalid dates:", test_scores_clean["date_clean"].isna().sum())

Invalid dates: 6783

In [38]:
test_scores_clean[["date", "date_clean"]].head(20)

           date date_clean
0    2025/05/05 2025-05-05
1    01.07.2025        NaT
2   06-Mar-2026        NaT
3    2025-05-25        NaT
4    2026-03-18        NaT
5    2025-07-29        NaT
6    15.01.2026        NaT
7    12.02.2026        NaT
8    2025-06-03        NaT
9    2026-01-11        NaT
10   01.06.2025        NaT
11   04/11/2025        NaT
12  10-Apr-2025        NaT
13   26/02/2026        NaT
14  18-Oct-2025        NaT
15   2025-07-25        NaT
16   2026-03-21        NaT
17   2025/06/30 2025-06-30
18   06-11-2025        NaT
19  11-Dec-2025        NaT

In [39]:
test_scores_clean["date_clean"] = pd.to_datetime(
    test_scores_clean["date"],
    errors="coerce",
    format="mixed"
)

In [40]:
print("Invalid dates:", test_scores_clean["date_clean"].isna().sum())

Invalid dates: 0

In [41]:
test_scores_clean[["date", "date_clean"]].head(20)

           date date_clean
0    2025/05/05 2025-05-05
1    01.07.2025 2025-01-07
2   06-Mar-2026 2026-03-06
3    2025-05-25 2025-05-25
4    2026-03-18 2026-03-18
5    2025-07-29 2025-07-29
6    15.01.2026 2026-01-15
7    12.02.2026 2026-12-02
8    2025-06-03 2025-06-03
9    2026-01-11 2026-01-11
10   01.06.2025 2025-01-06
11   04/11/2025 2025-04-11
12  10-Apr-2025 2025-04-10
13   26/02/2026 2026-02-26
14  18-Oct-2025 2025-10-18
15   2025-07-25 2025-07-25
16   2026-03-21 2026-03-21
17   2025/06/30 2025-06-30
18   06-11-2025 2025-06-11
19  11-Dec-2025 2025-12-11

In [48]:
def parse_date(value):
    value = str(value).strip()

    # YYYY-MM-DD or YYYY/MM/DD
    if len(value) >= 10 and value[4] in ["-", "/"]:
        return pd.to_datetime(value, errors="coerce", yearfirst=True)

    # DD.MM.YYYY
    if "." in value:
        return pd.to_datetime(
            value,
            format="%d.%m.%Y",
            errors="coerce"
        )

    # DD/MM/YYYY
    if "/" in value:
        return pd.to_datetime(
            value,
            format="%d/%m/%Y",
            errors="coerce"
        )

    # Dates containing month names, e.g. 06-Mar-2026
    if any(char.isalpha() for char in value):
        return pd.to_datetime(
            value,
            format="%d-%b-%Y",
            errors="coerce"
        )

    # Numeric dates containing hyphens
    if "-" in value:
        parts = value.split("-")

        if len(parts) == 3:
            first = int(parts[0])
            second = int(parts[1])

            # MM-DD-YYYY, e.g. 10-20-2025
            if second > 12:
                return pd.to_datetime(
                    value,
                    format="%m-%d-%Y",
                    errors="coerce"
                )

            # DD-MM-YYYY, e.g. 06-11-2025
            return pd.to_datetime(
                value,
                format="%d-%m-%Y",
                errors="coerce"
            )

    return pd.NaT


test_scores_clean["date_clean"] = test_scores_clean["date"].apply(parse_date)

In [49]:
print(
    "Invalid dates:",
    test_scores_clean["date_clean"].isna().sum()
)

Invalid dates: 0

In [50]:
print("Date range:")
print("Earliest:", test_scores_clean["date_clean"].min())
print("Latest:", test_scores_clean["date_clean"].max())

Date range:
Earliest: 2025-01-04 00:00:00
Latest: 2026-12-03 00:00:00

In [51]:
test_scores_clean[["date", "date_clean"]].sample(20, random_state=42)

             date date_clean
2215  19-Jun-2025 2025-06-19
2582   09-09-2025 2025-09-09
1662   2025-06-18 2025-06-18
3027   2025-05-10 2025-05-10
4343   13/12/2025 2025-12-13
2680   02-15-2026 2026-02-15
1765   2025/12/24 2025-12-24
1123   2026/03/28 2026-03-28
4054   2025-08-16 2025-08-16
3761   23/12/2025 2025-12-23
1535   09/10/2025 2025-10-09
2944   10/01/2026 2026-01-10
2987  21-Jun-2025 2025-06-21
4291   2025-04-16 2025-04-16
4342  29-Aug-2025 2025-08-29
4424   2025/06/27 2025-06-27
7941   25.03.2026 2026-03-25
4997   09.11.2025 2025-11-09
2748   2026/03/18 2026-03-18
2302   10.01.2026 2026-01-10

In [52]:
test_scores_clean["date_clean"] = test_scores_clean["date_clean"].dt.date

In [53]:
test_scores_clean[["date", "date_clean"]].head()

          date  date_clean
0   2025/05/05  2025-05-05
1   01.07.2025  2025-07-01
2  06-Mar-2026  2026-03-06
3   2025-05-25  2025-05-25
4   2026-03-18  2026-03-18

## Step 3 — School ID Standardization

The `school_id` column contains multiple representations of the same school,
such as:

- `SCH1001`
- `SCH-1001`
- `sch_1001`
- `S1001`
- `1001`

These variations can prevent accurate joins between datasets.

To ensure consistent joining across the project, all school identifiers are
standardized to the canonical format:

`SCH####`

The original `school_id` column is retained and a new `school_id_clean`
column is created for the standardized identifier.

In [54]:
test_scores_clean["school_id"].value_counts().head(20)

school_id
SCH0502    14
SCH0154    14
SCH0276    13
SCH0482    13
SCH0533    13
SCH0082    13
SCH0228    13
SCH0557    13
SCH0048    12
SCH0386    12
SCH0319    12
SCH0285    12
SCH0147    11
SCH0208    11
SCH0335    11
SCH0192    11
SCH0038    11
SCH0078    11
SCH0392    11
SCH0284    11
Name: count, dtype: int64

In [55]:
print("Unique school IDs:", test_scores_clean["school_id"].nunique())

Unique school IDs: 2800

In [56]:
print(
    test_scores_clean["school_id"]
    .astype(str)
    .head(20)
    .tolist()
)

['sch0083', 'sch0103', 'sch_0147', 'SCH0267', 'SCH0254', 'sch0362', 'SCH0148', 'SCH-0381', 'SCH0440', 'sch_0597', 'SCH0372', 'sch_0352', 'SCH-0087', 'SCH-0154', '0376', 'SCH0238', 'SCH0268', '0461', 'sch_0427', 'SCH-0439']

In [57]:
def standardize_school_id(value):
    value = str(value).strip().upper()

    # Remove common separators
    value = value.replace("-", "").replace("_", "")

    # Remove SCH prefix if present
    if value.startswith("SCH"):
        value = value[3:]

    # Remove S prefix if present
    elif value.startswith("S"):
        value = value[1:]

    # Keep the numeric part and restore leading zeros
    if value.isdigit():
        return "SCH" + value.zfill(4)

    return np.nan


test_scores_clean["school_id_clean"] = (
    test_scores_clean["school_id"].apply(standardize_school_id)
)

In [58]:
test_scores_clean[["school_id", "school_id_clean"]].head(30)

   school_id school_id_clean
0    sch0083         SCH0083
1    sch0103         SCH0103
2   sch_0147         SCH0147
3    SCH0267         SCH0267
4    SCH0254         SCH0254
5    sch0362         SCH0362
6    SCH0148         SCH0148
7   SCH-0381         SCH0381
8    SCH0440         SCH0440
9   sch_0597         SCH0597
10   SCH0372         SCH0372
11  sch_0352         SCH0352
12  SCH-0087         SCH0087
13  SCH-0154         SCH0154
14      0376         SCH0376
15   SCH0238         SCH0238
16   SCH0268         SCH0268
17      0461         SCH0461
18  sch_0427         SCH0427
19  SCH-0439         SCH0439
20     S0524         SCH0524
21   SCH0525         SCH0525
22   sch0214         SCH0214
23      0372         SCH0372
24   SCH0551         SCH0551
25     S0096         SCH0096
26   sch0552         SCH0552
27  sch_0496         SCH0496
28   SCH0590         SCH0590
29   SCH0396         SCH0396

In [59]:
print(
    "Missing standardized school IDs:",
    test_scores_clean["school_id_clean"].isna().sum()
)

Missing standardized school IDs: 0

In [60]:
print(
    "Unique standardized school IDs:",
    test_scores_clean["school_id_clean"].nunique()
)

Unique standardized school IDs: 600

In [61]:
school_id_mapping = (
    test_scores_clean[["school_id", "school_id_clean"]]
    .drop_duplicates()
    .sort_values("school_id_clean")
)

school_id_mapping.head(30)

     school_id school_id_clean
368    SCH0001         SCH0001
3582     S0001         SCH0001
4870   sch0001         SCH0001
5738      0001         SCH0001
6325  sch_0001         SCH0001
62     SCH0002         SCH0002
1391  SCH-0002         SCH0002
4414      0002         SCH0002
4828  sch_0002         SCH0002
327    SCH0003         SCH0003
2250     S0003         SCH0003
2776      0003         SCH0003
4164   sch0003         SCH0003
6282  sch_0003         SCH0003
7448  SCH-0003         SCH0003
959   SCH-0004         SCH0004
1982   SCH0004         SCH0004
2546      0004         SCH0004
2916     S0004         SCH0004
4988  sch_0004         SCH0004
43    sch_0005         SCH0005
290    SCH0005         SCH0005
1774     S0005         SCH0005
5061  SCH-0005         SCH0005
5413   sch0005         SCH0005
74     SCH0006         SCH0006
350   SCH-0006         SCH0006
1399     S0006         SCH0006
1532  sch_0006         SCH0006
1525  SCH-0007         SCH0007

In [62]:
mapping_counts = (
    test_scores_clean
    .groupby("school_id_clean")["school_id"]
    .nunique()
    .sort_values(ascending=False)
)

mapping_counts.head(20)

school_id_clean
SCH0023    6
SCH0590    6
SCH0594    6
SCH0027    6
SCH0030    6
SCH0573    6
SCH0361    6
SCH0368    6
SCH0370    6
SCH0372    6
SCH0558    6
SCH0044    6
SCH0045    6
SCH0047    6
SCH0572    6
SCH0343    6
SCH0373    6
SCH0334    6
SCH0378    6
SCH0380    6
Name: school_id, dtype: int64

## Step 4 — Subject Standardization

The raw dataset contains multiple names that refer to the same subject.

In particular:

- `Ganit` → `Math`
- `Mathematics` → `Math`
- `Math` → `Math`

The remaining subjects are retained as they appear in the dataset.

This reduces duplicate subject categories and ensures that mathematics
assessments are analyzed together.

A new `subject_clean` column is created while the original `subject` column
is retained for traceability.

In [63]:
test_scores_clean["subject"].value_counts()

subject
Hindi          1051
English        1022
Punjabi        1017
Ganit           996
EVS             994
Math            986
Mathematics     972
Science         962
Name: count, dtype: int64

In [64]:
subject_mapping = {
    "Ganit": "Math",
    "Mathematics": "Math"
}

test_scores_clean["subject_clean"] = (
    test_scores_clean["subject"]
    .replace(subject_mapping)
)

In [65]:
test_scores_clean["subject_clean"].value_counts()

subject_clean
Math       2954
Hindi      1051
English    1022
Punjabi    1017
EVS         994
Science     962
Name: count, dtype: int64

In [66]:
print(
    "Unique subjects before:",
    test_scores_clean["subject"].nunique()
)

print(
    "Unique subjects after:",
    test_scores_clean["subject_clean"].nunique()
)

Unique subjects before: 8
Unique subjects after: 6

## Handling Placeholder Values

The raw dataset uses string placeholders such as "NA" instead of actual missing values.
These placeholders are converted into proper missing values (`NaN`) for consistent analysis.

In [67]:
# Count placeholder values before cleaning

print("NA values in max_marks:")
print((test_scores_clean["max_marks"] == "NA").sum())

NA values in max_marks:
1983

In [68]:
test_scores_clean["max_marks"] = (
    test_scores_clean["max_marks"]
    .replace("NA", np.nan)
)

In [69]:
print("Missing values in max_marks:")
print(test_scores_clean["max_marks"].isna().sum())

Missing values in max_marks:
1983

## Missing Value Summary

After cleaning placeholder values, we inspect the dataset for remaining missing values.

In [70]:
missing_summary = (
    test_scores_clean.isna()
    .sum()
    .sort_values(ascending=False)
)

missing_summary

max_marks                  1983
date                          0
school_id                     0
grade                         0
assessment_id                 0
subject                       0
grading_scale                 0
avg_score                     0
total_students_assessed       0
score_percentage              0
date_clean                    0
school_id_clean               0
subject_clean                 0
dtype: int64

### Cleaning Decision

`max_marks` is missing only for records using the **Letter Grade** grading scale.

Since Letter Grade assessments do not use numerical maximum marks, these missing values are **structural missing values**, not data quality errors.

The values are intentionally kept as `NaN`.

# Final Validation Checks

In [72]:
print("Rows:", test_scores_clean.shape[0])
print("Columns:", test_scores_clean.shape[1])

print("\nDuplicate rows:", test_scores_clean.duplicated().sum())
print("Duplicate assessment IDs:",
      test_scores_clean["assessment_id"].duplicated().sum())

print("\nMissing values:")
print(test_scores_clean.isna().sum())

Rows: 8000
Columns: 13

Duplicate rows: 0
Duplicate assessment IDs: 0

Missing values:
assessment_id                 0
date                          0
school_id                     0
grade                         0
subject                       0
grading_scale                 0
avg_score                     0
max_marks                  1983
total_students_assessed       0
score_percentage              0
date_clean                    0
school_id_clean               0
subject_clean                 0
dtype: int64

In [77]:
# Keep only the cleaned columns for downstream analysis

test_scores_final = test_scores_clean.copy()

test_scores_final = test_scores_final.drop(
    columns=["date", "school_id", "subject"]
)

test_scores_final = test_scores_final.rename(
    columns={
        "date_clean": "date",
        "school_id_clean": "school_id",
        "subject_clean": "subject"
    }
)

test_scores_final.to_csv(
    "../data/processed/test_scores_clean.csv",
    index=False
)

print("Cleaned dataset saved successfully!")

Cleaned dataset saved successfully!

In [74]:
test_scores_clean["max_marks"] = pd.to_numeric(
    test_scores_clean["max_marks"],
    errors="coerce"
)

In [75]:
print(test_scores_clean["max_marks"].dtype)

float64

In [76]:
test_scores_clean[["grading_scale", "max_marks"]].value_counts()

grading_scale  max_marks
CGPA           10.0         1609
%              100.0         816
pct            100.0         800
Percentage     100.0         790
Raw Marks      50.0          690
               25.0          657
               100.0         655
Name: count, dtype: int64